{% set name = "streamlit-pdf" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 51911d7f4c33837f934cc2343a1c1628ee5b2d4c8751a1adbe7b3da221ff2ae0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=61
  run:
    - python
  run_constrained:
    - streamlit >=1.51.0

# Skipped end-to-end tests, need to build frontend with npm.
# Skipped check UI tests with Chrome browser, not all build targets support it.
test:
  imports:
    - streamlit_pdf
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  requires:
    - pip

about:
  home: https://streamlit.io
  summary: A Streamlit component for viewing PDF files
  license: BSD-3-Clause AND Apache-2.0
  license_family: Other
  license_file:
    - LICENSE
    - streamlit_pdf/frontend/build/assets/cmaps/LICENSE
  description: |
    A lightweight Streamlit feature that seamlessly displays PDF files in your apps,
    allowing for simple, responsive, and clean document viewing with minimal effort.
  dev_url: https://github.com/streamlit/streamlit-pdf
  doc_url: https://github.com/streamlit/streamlit-pdf/blob/main/README.md

extra:
  recipe-maintainers:
    - snegireff
